#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

SCOPES="https://www.googleapis.com/auth/googlehealth.sleep.readonly https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly"
REDIRECT_URI="http://localhost"
FIXTURES="${FIXTURES:-/tmp/deskhud-google-health}"

banner "Google Health API setup for the deskhud sleep Module"

stage "Cloud project + API"
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: deskhud → Create. Make sure it's selected in the top bar."
pause "Project created and selected?"
open_url "https://console.cloud.google.com/apis/library/health.googleapis.com"
step "Click Enable on 'Google Health API'."
pause "Enabled?"

stage "OAuth consent screen"
open_url "https://console.cloud.google.com/auth/overview"
step "Get started → App name: deskhud, support email: yours → Next."
step "Audience: External → Next."
step "Contact email: yours → Next → agree to the policy → Create."
pause "Consent screen created?"

stage "Scopes"
open_url "https://console.cloud.google.com/auth/scopes"
step "Add or remove scopes → 'Manually add scopes', paste these two (one per line):"
for s in $SCOPES; do note "  $s"; done
step "Add to table → Update → Save."
note "They'll be listed under 'Restricted scopes'. That's expected."
pause "Scopes saved?"

stage "Publish (In production)"
say "In Testing, refresh tokens die after 7 days. In production (unverified) they don't."
open_url "https://console.cloud.google.com/auth/audience"
step "Publishing status: Testing → Publish app → Confirm."
note "Don't submit for verification; personal use under 100 users skips it."
warn "If Google blocks publishing, add yourself under Test users instead."
warn "The token will then expire in 7 days, and this plan doesn't work."
pause "Status is 'In production'?"

stage "OAuth client"
open_url "https://console.cloud.google.com/auth/clients/create"
step "Application type: Web application, name: deskhud."
step "Authorized redirect URIs → Add URI: $REDIRECT_URI → Create."
step "Copy the Client ID and Client secret from the dialog."
ask GOOGLE_HEALTH_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_HEALTH_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_HEALTH_CLIENT_ID "$GOOGLE_HEALTH_CLIENT_ID"
write_env GOOGLE_HEALTH_CLIENT_SECRET "$GOOGLE_HEALTH_CLIENT_SECRET"

stage "Authorize + refresh token"
auth_url="https://accounts.google.com/o/oauth2/v2/auth?$(jq -rn \
  --arg client_id "$GOOGLE_HEALTH_CLIENT_ID" --arg redirect_uri "$REDIRECT_URI" --arg scope "$SCOPES" \
  '{client_id: $client_id, redirect_uri: $redirect_uri, scope: $scope, response_type: "code", access_type: "offline", prompt: "consent"}
   | to_entries | map("\(.key)=\(.value | @uri)") | join("&")')"
open_url "$auth_url"
step "Sign in with the Google account your Fitbit Air syncs to."
step "'Google hasn't verified this app' → Advanced → Go to deskhud (unsafe)."
step "Tick both Google Health permissions → Continue."
step "The redirect to localhost fails to load. That's fine: copy the whole address bar."
ask REDIRECT "Paste the redirected URL:"
code=$(jq -rn --arg url "$REDIRECT" '$url | capture("[?&]code=(?<c>[^&]+)").c')
code=$(printf '%b' "${code//%/\\x}")
tokens=$(curl -sS https://oauth2.googleapis.com/token \
  --data-urlencode "code=$code" \
  --data-urlencode "client_id=$GOOGLE_HEALTH_CLIENT_ID" \
  --data-urlencode "client_secret=$GOOGLE_HEALTH_CLIENT_SECRET" \
  --data-urlencode "redirect_uri=$REDIRECT_URI" \
  --data-urlencode "grant_type=authorization_code")
GOOGLE_HEALTH_REFRESH_TOKEN=$(jq -r '.refresh_token // empty' <<<"$tokens")
if [[ -z "$GOOGLE_HEALTH_REFRESH_TOKEN" ]]; then
  warn "No refresh token in the response:"
  jq 'del(.access_token)' <<<"$tokens"
  exit 1
fi
write_env GOOGLE_HEALTH_REFRESH_TOKEN "$GOOGLE_HEALTH_REFRESH_TOKEN"
expires=$(jq -r '.refresh_token_expires_in // empty' <<<"$tokens")
if [[ -n "$expires" ]]; then
  warn "Refresh token expires in $((expires / 86400)) days: the app is still in Testing."
  SKIPPED+=("Get a non-expiring refresh token (publish the app, then re-run)")
else
  printf '  %s✓ refresh token has no expiry%s\n' "$GREEN" "$RESET"
fi
note "Granted: $(jq -r .scope <<<"$tokens")"
pause

stage "Verify + save sample responses"
access=$(curl -sS https://oauth2.googleapis.com/token \
  --data-urlencode "client_id=$GOOGLE_HEALTH_CLIENT_ID" \
  --data-urlencode "client_secret=$GOOGLE_HEALTH_CLIENT_SECRET" \
  --data-urlencode "refresh_token=$GOOGLE_HEALTH_REFRESH_TOKEN" \
  --data-urlencode "grant_type=refresh_token" | jq -r .access_token)
since=$(date -d '7 days ago' +%F 2>/dev/null || date -v-7d +%F)
mkdir -p "$FIXTURES"
fetch() { # dataType filter
  curl -sS -G "https://health.googleapis.com/v4/users/me/dataTypes/$1/dataPoints" \
    -H "Authorization: Bearer $access" --data-urlencode "filter=$2" -o "$FIXTURES/$1.json"
  printf '  %s✓%s %s: %s data points → %s\n' "$GREEN" "$RESET" "$1" \
    "$(jq -r 'if .error then "error: \(.error.message)" else (.dataPoints // [] | length) end' "$FIXTURES/$1.json")" "$FIXTURES/$1.json"
}
fetch sleep "sleep.interval.civil_end_time >= \"$since\""
fetch daily-heart-rate-variability "daily_heart_rate_variability.date >= \"$since\""
note "Sample responses hold health data: keep them out of the repo."
pause

finish
say "For the NAS: copy the three GOOGLE_HEALTH_* lines from $ENV_FILE into deskhud.env."
